# Generated by Django 6.0.3 on 2026-03-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_favoritelist_favoriteitem_delete_favorite'),
        ('tweets', '0003_rename_parent_tweet_reply_to_alter_tweet_author_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteitem',
            unique_together={('list', 'tweet')},
        ),
    ]
